### ISSUE TITLE
Is that a convention, lower-case file name in plural, class name in singular?

### ISSUE THREAD

**Issue by JJ** [tbrowder/CSV-AutoClass#3]
Are there any other conventions at play here?

**Comment by tbrowder** [comment]
Yes, but I need to emphasize that more. Perhaps I can improve that, maybe use an INI or JSON or YAML file. There are modules JSON::Class and JSON::Infer that I should take some ideas from.

How are you, JJ?

**Comment by JJ** [comment]
Fine, thank you! Checking out your great work!
Maybe then could I suggest some changes in the README.md file?

**Comment by tbrowder** [comment]
Glad to hear-- and thanks for the kind words!

Ref docs:  Of course!  PRs are welcome. NOTE: The source of the README.md is Rakupod in `./docs/README.rakudoc`.

**Comment by tbrowder** [comment]
BTW, your concern may be premature. I am now working on a new module which should make this one obsolete.  It's on my account here as CSV::Parser::Simple and is similar, but simpler and better, to @tony-o's CSV::Parser (which has bugs and feature request he hasn't handled) .

My new module will:

1. Have a class that parses a CSV file.
2. Have a method that produces a class definition from the same CSV file and the user can name the calls as he wishes.
3. Replace CSV::AutoClass

**Comment by JJ** [comment]
Great!

**Comment by tbrowder** [comment]
Overcome by events. I have renamed this to CSV-Autoclass (vs AutoClass).

I have also improved the README per your comments here.
